### PR TITLE
Fixes and stuff to the gun system

### PR DESCRIPTION
**Pull request by dark00shadow**

### CODE REVIEW

**Comment by arthuro555** [comment]
I resolved the conflicts quickly I think I broke it in the rooms scene, can you check and potentially repair it?

**Comment by dark00shadow** [comment]
> I resolved the conflicts quickly I think I broke it in the rooms scene, can you check and potentially repair it?

idk how they work in json file way

**Comment by arthuro555** [comment]
> idk how they work in json file way

I modified the json but the json is openable by gdevelop ;) just open in GDevelop and playtest to see if it's working as intended, and modify the events if I modified them by accident

**Comment by dark00shadow** [comment]
> > idk how they work in json file way
> 
> I modified the json but the json is openable by gdevelop ;) just open in GDevelop and playtest to see if it's working as intended, and modify the events if I modified them by accident

did it change my branch to?

**Pull request closed without merging**
