### PR TITLE
Rebuild game map in Tiled

### PR DESCRIPTION
**Pull request by TheGemDev**
Rebuilding the entire game map in tiled.
Screenshot 2021-05-24 213028

### CODE REVIEW

**Comment by arthuro555** [comment]
That screenshot looks... less complete than what we had before?

**Comment by TheGemDev** [comment]
something

> That screenshot looks... less complete than what we had before?

yes, it does. I am rebuilding the map we made in gdevelop earlier in tiled now. A problem with the tileset delayed the process, hopefully it's solved now. 

I just realized I committed an empty overworld.json i would try to fix that as soon as possible.

**Comment by arthuro555** [comment]
Ah, it is not finished? My bad then. Btw I am working on the game too live on the GDevelop discord chat if you are interested.

**Comment by TheGemDev** [comment]
Screenshot 2021-05-24 223525

**Comment by TheGemDev** [comment]
> Ah, it is not finished? My bad then. Btw I am working on the game too live on the GDevelop discord chat if you are interested.

sorry, i missed your message, i would have loved to watch

**Comment by TheGemDev** [comment]
ffdg

**Comment by TheGemDev** [comment]
more roads :)
Screenshot (9)
Screenshot (8)

**Comment by TheGemDev** [comment]
Screenshot (10)

**Pull request closed without merging**
