### PR TITLE
Added World border

### PR DESCRIPTION
**Pull request by Midhil457**
Changes:
- Added world border

- the border is hidden when the game is running

- The player can't pass beyond the world border

- Added world border assets (Can be found in the 'assets/sprite_object" folder)

World_border

### CODE REVIEW

**Review by TheGemDev — COMMENTED** [review]
consider using a black sprite object for the border.

**Review by TheGemDev — CHANGES_REQUESTED** [review]
consider using a "black" color sprite for the border

**Comment by Midhil457** [comment]
Yes, I should have. I was trying to make the yellow and black stripes as an Easter egg. But, didn't.But, they will be hidden during run time

**Comment by Midhil457** [comment]
I will try to change it up when I get time

**Comment by Midhil457** [comment]
Fixed the colour of the border ;)

**Comment by TheGemDev** [comment]
looks great:+1:, but this won't be merged yet due to the sudden change of recreating the map in tiled.

**Comment by arthuro555** [comment]
I can merge this once the conflict has been resolved.

**Comment by Midhil457** [comment]
Is there something I can do to fix the conflicts?

**Comment by arthuro555** [comment]
Yes, to fix a conflict, you need to merge the main branch (named `master` on this repo) into your branch. Then, while merging, git will error out asking you to fix conflicts. You then must open the JSON files (I recommend with VSCode) that git said had conflicts, then find sections that look like 
```
>>>>>>>>>>>>>>>>> master
Some JSON
--------------------------------------
Some other JSON
<<<<<<<<<<<<<<<<< World_border
```
The `------------------` separates the version on master and your version. You will need to combine both yourself, and then commit all changes.

**Comment by Midhil457** [comment]
I think I did everything right

**Pull request closed without merging**
