### PR TITLE
Added 4 new rooms and made new "You lose" scene

### PR DESCRIPTION
**Pull request by Midhil457**
- Added 4 new rooms (making it 10 different rooms in the current version of the game). They are a bit big. 
  - Added tiled version for some floor objects.

Capture1

- Made a new "You lose" scene for fixing build issues
  - Added a "black and white" and "zoom blur" effect.
  - Added a new "Wasted" text
  More work is need for this. It will be done later.
- Fixed Github build. By removing bbtext from "Overworld" scene

Captue2

### CODE REVIEW

**Comment by Midhil457** [comment]
> i moved the font into the assets folder :)

Oh, I did not know that. Won't it mess up the path?

**Review by arthuro555 — COMMENTED** [review]
After a quick look at the few 1000 lines I don't see anything that looks malicious, but I cannot review a full 6000 lines of changes. I neither have enough time, not do I want to invest all my time in this one thing. Please next time keep the changes smaller (one change at a time).

**Review by TheGemDev — APPROVED** [review]

**Review by TheGemDev — APPROVED** [review]

**Review by TheGemDev — APPROVED** [review]

**Comment by TheGemDev** [comment]
looks good :+1:

**Comment by Midhil457** [comment]
Oh, I forgot to tell, I didn't link up the rooms to the overworld as I did not know how it worked

**Comment by TheGemDev** [comment]
I would do the linking as soon as the rooftops are complete

**Pull request merged**
